basePath: /
definitions:
  dto.AuthResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/infrastructure.User'
    type: object
  dto.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dto.GuestLoginRequest:
    properties:
      android_id:
        type: string
      username:
        type: string
    required:
    - android_id
    - username
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  infrastructure.User:
    properties:
      android_id:
        description: Add unique index
        type: string
      created_at:
        type: string
      email:
        description: Make nullable
        type: string
      google_id:
        description: Add unique index
        type: string
      id:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
  level.CompleteLevelByNumberRequest:
    properties:
      level_number:
        type: integer
      user_id:
        type: integer
    type: object
  level.CompleteLevelRequest:
    properties:
      level_id:
        type: integer
      user_id:
        type: integer
    type: object
  level.LevelRequest:
    properties:
      level_number:
        type: integer
      plant_name:
        type: string
      reward:
        type: integer
      riddle:
        type: string
    type: object
  level.Response:
    properties:
      data: {}
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: sushilawasthi2999@gmail.com
    name: Sushil Awasthi
  description: Backend API for the PlantGo system
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://wtfisterms.com/terms/
  title: PlantGo API
  version: "1.0"
paths:
  /:
    get:
      description: Basic test route
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello World
      tags:
      - Utility
  /admin/levels:
    post:
      consumes:
      - application/json
      description: Creates a new level with riddle, plant name, and reward
      parameters:
      - description: Level creation info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/level.LevelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Create a new level
      tags:
      - Admin
  /admin/levels/{id}:
    delete:
      description: Deletes a level by ID
      parameters:
      - description: Level ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Delete level
      tags:
      - Admin
    put:
      consumes:
      - application/json
      description: Updates an existing level by ID
      parameters:
      - description: Level ID
        in: path
        name: id
        required: true
        type: integer
      - description: Level update info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/level.LevelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Update level
      tags:
      - Admin
  /auth/google/callback:
    get:
      description: Processes the OAuth2 callback from Google and returns a JWT token
      parameters:
      - description: Authorization code from Google
        in: query
        name: code
        required: true
        type: string
      - description: State token
        in: query
        name: state
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Handle Google OAuth callback
      tags:
      - Auth
  /auth/google/login:
    get:
      description: Redirects the user to Google's OAuth2 authorization page
      produces:
      - text/plain
      responses:
        "307":
          description: Redirects to Google OAuth2 page
          schema:
            type: string
      summary: Initiate Google OAuth login
      tags:
      - Auth
  /auth/guest/login:
    post:
      consumes:
      - application/json
      description: Authenticates or creates a guest user using Android ID and username
      parameters:
      - description: Guest login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.GuestLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Guest login
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user with username, email, and password
      parameters:
      - description: User registration info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Register a new user
      tags:
      - Auth
  /game/complete:
    post:
      consumes:
      - application/json
      description: Marks a level as completed for a user
      parameters:
      - description: Level completion info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/level.CompleteLevelRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Complete level
      tags:
      - Game
  /game/complete-by-number:
    post:
      consumes:
      - application/json
      description: Marks a level as completed for a user using level number
      parameters:
      - description: Level completion info
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/level.CompleteLevelByNumberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Complete level by number
      tags:
      - Game
  /game/completed/{userId}:
    get:
      description: Retrieves all levels completed by a user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get completed levels
      tags:
      - Game
  /game/data/{userId}:
    get:
      description: Retrieves comprehensive game data for a user including progress
        and rewards
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get game data
      tags:
      - Game
  /game/level/{userId}/{number}:
    get:
      description: Retrieves detailed information about a level for a specific user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: Level Number
        in: path
        name: number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get level details
      tags:
      - Game
  /game/progress/{userId}:
    get:
      description: Retrieves the progress of a user across all levels
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get user progress
      tags:
      - Game
  /game/rewards/{userId}:
    get:
      description: Retrieves the total reward points for a user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get user reward
      tags:
      - Game
  /health:
    get:
      description: Returns database and service health
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - System
  /levels:
    get:
      description: Retrieves all levels in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get all levels
      tags:
      - Level
  /levels/{id}:
    get:
      description: Retrieves a level by its ID
      parameters:
      - description: Level ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get level by ID
      tags:
      - Level
  /levels/number/{number}:
    get:
      description: Retrieves a level by its level number
      parameters:
      - description: Level Number
        in: path
        name: number
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/level.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/level.Response'
      summary: Get level by number
      tags:
      - Level
  /plant/health:
    get:
      description: Returns the health status of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/level.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/level.Response'
      summary: Health check
      tags:
      - System
  /profile:
    get:
      description: Returns the authenticated user's profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/infrastructure.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get user profile
      tags:
      - Auth
  /scan/image:
    post:
      consumes:
      - multipart/form-data
      description: Accepts real-time image uploads for scanning
      parameters:
      - description: Image to scan
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Process scanned image
      tags:
      - Scanner
  /scan/video:
    get:
      consumes:
      - application/json
      description: WebSocket endpoint for real-time video frame processing
      produces:
      - application/json
      responses:
        "101":
          description: Switching Protocols
          schema:
            type: string
      summary: Process live video stream
      tags:
      - Scanner
swagger: "2.0"
